# fly.toml app configuration file generated for potholes on 2024-11-04T13:55:29-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'potholes'
primary_region = 'ewr'

[env]
  AWS_ENDPOINT_URL_S3="https://t3.storage.dev"
  AWS_ENDPOINT_URL_IAM="https://fly.iam.storage.tigris.dev"
  AWS_REGION="auto"

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-2x'
